language: php

php:
    - 7.0
    - 7.1
    - 7.2

before_install:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi;'
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - curl -s http://getcomposer.org/installer | php

install:
    - php composer.phar install

script: bin/phpunit
